name: Odoo Code Quality Check

on:
  push:
    branches: ["workflow"]
  pull_request:
    branches: ["workflow"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Linters
        run: |
          pip install black flake8 pylint pylint-odoo

      - name: Run Black (format check)
        run: black --check . || true

      - name: Run Flake8
        run: flake8 .

      - name: Run Pylint with Odoo plugin
        run: pylint --load-plugins=pylint_odoo .

      - name: Push latest commit to dev branch
        if: success()
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin dev
          git checkout dev
          git cherry-pick workflow
          git push origin dev